<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import math

In [67]:
#Матрица собственных чисел:
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, 6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 7]])
print(lambda_matrix)

[[3 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 7]]


In [68]:
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
L_ = np.linalg.inv(L)
print(L)
print(L_)

[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [69]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print(A)

[[  -6.    6.    0.    0.]
 [ -18.   15.    0.    0.]
 [-563.  344.  -47.   72.]
 [-391.  238.  -36.   55.]]


In [70]:
#дано
B = np.matrix([[1, -2], [0, 5],[7, -9],[0, 2]])
C = np.matrix([-8, -4, 1, 0])
x0 = np.matrix([0, -7, 8, -1]).T
print(B)
print(C)
print(x0)

[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
[[-8 -4  1  0]]
[[ 0]
 [-7]
 [ 8]
 [-1]]


In [72]:
#составление матрицы управляемости
print(B)

AB = A.dot(B)
print(AB)

AAB = A.dot(A).dot(B)
print(AAB)

AAAB = A.dot(A).dot(A).dot(B)
print(AAAB)

[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
[[  -6.   42.]
 [ -18.  111.]
 [-892. 3413.]
 [-643. 2406.]]
[[  -72.   414.]
 [ -162.   909.]
 [-7186. 27359.]
 [-5191. 19458.]]
[[  -540.   2970.]
 [ -1134.   6183.]
 [-51202. 194717.]
 [-37213. 139734.]]


In [73]:
#матрица управляемости
beta = np.concatenate((B, AB, AAB, AAAB), axis=1)
print(pd.DataFrame(beta))

     0    1      2       3       4        5        6         7
0  1.0 -2.0   -6.0    42.0   -72.0    414.0   -540.0    2970.0
1  0.0  5.0  -18.0   111.0  -162.0    909.0  -1134.0    6183.0
2  7.0 -9.0 -892.0  3413.0 -7186.0  27359.0 -51202.0  194717.0
3  0.0  2.0 -643.0  2406.0 -5191.0  19458.0 -37213.0  139734.0


In [74]:
rang_beta = np.linalg.matrix_rank(beta)
print(rang_beta)

4


In [75]:
#проверка для 1.15
print(B[:,0])
AB1 = A.dot(B[:,0])
print(AB1)
AAB1 = A.dot(A).dot(B[:,0])
print(AAB1)
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

[[1]
 [0]
 [7]
 [0]]
[[  -6.]
 [ -18.]
 [-892.]
 [-643.]]
[[  -72.]
 [ -162.]
 [-7186.]
 [-5191.]]
[[  -540.]
 [ -1134.]
 [-51202.]
 [-37213.]]


In [76]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print(pd.DataFrame(beta1))

     0      1       2        3
0  1.0   -6.0   -72.0   -540.0
1  0.0  -18.0  -162.0  -1134.0
2  7.0 -892.0 -7186.0 -51202.0
3  0.0 -643.0 -5191.0 -37213.0


In [77]:
rang_beta1 = np.linalg.matrix_rank(beta)
print(rang_beta1)

4


In [84]:
#матрица наблюдаемости
A_arr = A
C_arr = C.T
print(C_arr)

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print(AC)
print(AAC)
print(AAAC)

[[-8]
 [-4]
 [ 1]
 [ 0]]
[[  24.]
 [  84.]
 [3081.]
 [2140.]]
[[  360.]
 [  828.]
 [24657.]
 [17392.]]
[[  2808.]
 [  5940.]
 [175497.]
 [125212.]]


In [86]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print(pd.DataFrame(gamma))

     0       1        2         3
0 -8.0    24.0    360.0    2808.0
1 -4.0    84.0    828.0    5940.0
2  1.0  3081.0  24657.0  175497.0
3  0.0  2140.0  17392.0  125212.0


In [102]:
#пункт 1.15
#1)
I = np.eye(4)
D0 = I
print(D0)

d1 = np.round(-np.trace(D0.dot(A)))
print(d1)
D1 = D0 + d1 * I
print(D1)

d2 = np.round(-0.5 * np.trace(D1.dot(A)))
print(d2)
D2 = D1 + d2 * I
print(D2)

d3 = np.round(-(1.0 / 3.0) * np.trace(D2.dot(A)))
print(d3)
D3 = D2 + d3 * I
print(D3)

d4 = np.round(-(1.0 / 4.0) * np.trace(D3.dot(A)))
print(d4)

check = D3.dot(A) + d4 * I
print(check)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-17.0
[[-16.   0.   0.   0.]
 [  0. -16.   0.   0.]
 [  0.   0. -16.   0.]
 [  0.   0.   0. -16.]]
136.0
[[120.   0.   0.   0.]
 [  0. 120.   0.   0.]
 [  0.   0. 120.   0.]
 [  0.   0.   0. 120.]]
-680.0
[[-560.    0.    0.    0.]
 [   0. -560.    0.    0.]
 [   0.    0. -560.    0.]
 [   0.    0.    0. -560.]]
2380.0
[[   5740.   -3360.       0.       0.]
 [  10080.   -6020.       0.       0.]
 [ 315280. -192640.   28700.  -40320.]
 [ 218960. -133280.   20160.  -28420.]]


In [105]:
S4 = B[:,0]
S3 = A.dot(S4) + d1 * B[:,0]
S2 = A.dot(S3) + d2 * B[:,0]
S1 = A.dot(S2) + d3 * B[:,0]
print(S1)
print(S2)
print(S3)
print(S4)
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_))

[[  -812.]
 [  -828.]
 [-55112.]
 [-36414.]]
[[ 166.]
 [ 144.]
 [8930.]
 [5740.]]
[[  -23.]
 [  -18.]
 [-1011.]
 [ -643.]]
[[1]
 [0]
 [7]
 [0]]
         0       1       2    3
0   -812.0   166.0   -23.0  1.0
1   -828.0   144.0   -18.0  0.0
2 -55112.0  8930.0 -1011.0  7.0
3 -36414.0  5740.0  -643.0  0.0
          0         1         2         3
0 -0.009035  0.013935  0.001291 -0.002096
1 -0.103630  0.099896  0.014804 -0.022367
2 -0.413427  0.102599  0.059061 -0.082502
3  1.357277 -2.907681 -0.051040  0.113098


In [ ]:
#2)