<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import math

In [13]:
#Матрица собственных чисел:
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, 6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 7]])
print(lambda_matrix)

[[3 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 7]]


In [14]:
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
L_ = np.linalg.inv(L)
print(L)
print(L_)

[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [15]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print(A)

[[  -6.    6.    0.    0.]
 [ -18.   15.    0.    0.]
 [-563.  344.  -47.   72.]
 [-391.  238.  -36.   55.]]
