<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import pandas as pd
import numpy as np

In [48]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, 6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2], [0, 5],[7, -9],[0, 2]])
C = np.matrix([-8, -4, 1, 0])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[3 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 0]]
L = 
[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
B = 
[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
C = 
[[-8 -4  1  0]]


In [49]:
print('det(L) = ' + str(np.linalg.det(L)))

det(L) = 0.9999999999999991


In [50]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [51]:
print("L * L_обр = ")
print(pd.DataFrame(np.round(L.dot(L_))))

L * L_обр = 
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0 -0.0  1.0  0.0
3  0.0  0.0 -0.0  1.0


In [52]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(np.round(A))

A = 
[[ -6.   6.   0.   0.]
 [-18.  15.   0.   0.]
 [ 81. -48.   9. -12.]
 [ 92. -56.   6.  -8.]]


In [53]:
#дополнительные вычисления для составления матрицы управляемости

AB = A.dot(B)
print("A * B = ")
print(AB)
print("\n")

AAB = A.dot(A).dot(B)
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = A.dot(A).dot(A).dot(B)
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[  -6.   42.]
 [ -18.  111.]
 [ 144. -507.]
 [ 134. -534.]]


A * A * B = 
[[  -72.   414.]
 [ -162.   909.]
 [   66.   -81.]
 [  248. -1122.]]


A * A * A * B = 
[[ -540.  2970.]
 [-1134.  6183.]
 [ -438.  2637.]
 [  860. -4326.]]


In [54]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

{A,B} = 
     0    1      2      3      4       5       6       7
0  1.0 -2.0   -6.0   42.0  -72.0   414.0  -540.0  2970.0
1  0.0  5.0  -18.0  111.0 -162.0   909.0 -1134.0  6183.0
2  7.0 -9.0  144.0 -507.0   66.0   -81.0  -438.0  2637.0
3  0.0  2.0  134.0 -534.0  248.0 -1122.0   860.0 -4326.0


In [55]:
rang_beta = np.linalg.matrix_rank(beta)
print("Ранг матрицы управляемости rg {A,B} = " + str(rang_beta))

Ранг матрицы управляемости rg {A,B} = 4


In [56]:
#проверка для 1.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[ -6.]
 [-18.]
 [144.]
 [134.]]


A * A * B_1 = 
[[ -72.]
 [-162.]
 [  66.]
 [ 248.]]


A * A * A * B_1 = 
[[ -540.]
 [-1134.]
 [ -438.]
 [  860.]]


In [57]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0      1      2       3
0  1.0   -6.0  -72.0  -540.0
1  0.0  -18.0 -162.0 -1134.0
2  7.0  144.0   66.0  -438.0
3  0.0  134.0  248.0   860.0

Ранг матрицы управляемости rg {A,B_1} = 4


In [58]:
#дополнительные вычисления для матрицы наблюдаемости
A_arr = A.T
C_arr = C.T

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print("A * C = ")
print(AC)
print('\n')

print("A * A * C = ")
print(AAC)
print('\n')
print("A * A * A * C = ")
print(AAAC)
print('\n')

A * C = 
[[ 201.]
 [-156.]
 [   9.]
 [ -12.]]


A * A * C = 
[[1227.]
 [-894.]
 [   9.]
 [ -12.]]


A * A * A * C = 
[[ 8355.]
 [-5808.]
 [    9.]
 [  -12.]]




In [59]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print('{A, С} = ')
print(pd.DataFrame(gamma))
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C} = " + str(rang_gamma))

{A, С} = 
     0      1       2       3
0 -8.0  201.0  1227.0  8355.0
1 -4.0 -156.0  -894.0 -5808.0
2  1.0    9.0     9.0     9.0
3  0.0  -12.0   -12.0   -12.0

Ранг матрицы наблюдаемости rg {A,C} = 4


In [69]:
#пункт 1.15
#1) 
d1 = 1
d2 = -10
d3 = 27
d4 = -18

In [70]:
#нахождение матрицы S
S4 = B[:,0]
S3 = A.dot(S4) + d1 * B[:,0]
S2 = A.dot(S3) + d2 * B[:,0]
S1 = A.dot(S2) + d3 * B[:,0]
print('S_1 = ')
print(S1)
print('\nS_2 = ')
print(S2)
print('\nS_3 = ')
print(S3)
print('\nS_4 = ')
print(S4)
print('\nS = ')
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))
print('\nS_ = ')
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_))

S_1 = 
[[ -525.]
 [-1116.]
 [-1623.]
 [ -232.]]

S_2 = 
[[ -88.]
 [-180.]
 [ 140.]
 [ 382.]]

S_3 = 
[[ -5.]
 [-18.]
 [151.]
 [134.]]

S_4 = 
[[1]
 [0]
 [7]
 [0]]

S = 
        0      1      2    3
0  -525.0  -88.0   -5.0  1.0
1 -1116.0 -180.0  -18.0  0.0
2 -1623.0  140.0  151.0  7.0
3  -232.0  382.0  134.0  0.0

S_ = 
          0         1         2         3
0 -0.019364  0.004853  0.002766 -0.003188
1  0.172615 -0.051032 -0.024659  0.027374
2 -0.525606  0.153881  0.075087 -0.076091
3  3.396194 -1.173606 -0.342313  0.354816


In [71]:
print("S * S_обр = ")
pd.DataFrame(np.round(S.dot(S_)))

S * S_обр = 


0    1    2    3
0  1.0 -0.0 -0.0  0.0
1 -0.0  1.0 -0.0  0.0
2  0.0  0.0  1.0  0.0
3  0.0 -0.0  0.0  1.0

In [87]:
print('det(S) = ' + str(np.round(np.linalg.det(S))))

det(S) = -6233760.0


matrix([[ 1.207080e+05, -3.025200e+04, -1.724400e+04,  1.987200e+04],
        [-1.076040e+06,  3.181200e+05,  1.537200e+05, -1.706400e+05],
        [ 3.276504e+06, -9.592560e+05, -4.680720e+05,  4.743360e+05],
        [-2.117106e+07,  7.315980e+06,  2.133900e+06, -2.211840e+06]])

In [ ]:
#в пункте 2) надо самому разложить многочлен по примеру и коэффициенты при p будут равны соответствующим позициям для вектора d с чертой

In [73]:
#3-4) поиск матрицы K
K_ = np.matrix([0, 8, -80, 216]) #это K с чертой (ее можно найти с помощью пункта 2)
K = K_.dot(S_)
print("K = ")
print(K)

K = 
[[ 777.00739201 -266.21767922  -80.14391314   82.94663895]]


In [74]:
#5) поиск A с чертой
A_ = A - (B[:,0]).dot(K)
print('A_ = ')
print(A_)

A_ = 
[[ -783.00739201   272.21767922    80.14391314   -82.94663895]
 [  -18.            15.             0.             0.        ]
 [-5358.05174405  1815.52375452   570.00739201  -592.62647263]
 [   92.           -56.             6.            -8.        ]]


In [83]:
lambda1 = np.matrix([-8,1,3,6])
I = np.eye(4)
check1 = lambda1.dot(I) - A_
print('lambda * I - A_ =\n' + str(check1))
print('\ndet (lambda * I - A_) = ' + str(np.linalg.det(check1)))

lambda * I - A_ =
[[ 7.75007392e+02 -2.71217679e+02 -7.71439131e+01  8.89466389e+01]
 [ 1.00000000e+01 -1.40000000e+01  3.00000000e+00  6.00000000e+00]
 [ 5.35005174e+03 -1.81452375e+03 -5.67007392e+02  5.98626473e+02]
 [-1.00000000e+02  5.70000000e+01 -3.00000000e+00  1.40000000e+01]]

det (lambda * I - A_) = 3202079.265419288
