<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [4]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, 6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2], [0, 5],[7, -9],[0, 2]])
C = np.matrix([-8, -4, 1, 0])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[3 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 0]]
L = 
[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
B = 
[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
C = 
[[-8 -4  1  0]]


In [5]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [6]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(A)

A = 
[[ -6.   6.   0.   0.]
 [-18.  15.   0.   0.]
 [ 81. -48.   9. -12.]
 [ 92. -56.   6.  -8.]]


In [7]:
#дополнительные вычисления для составления матрицы управляемости

AB = A.dot(B)
print("A * B = ")
print(AB)
print("\n")

AAB = A.dot(A).dot(B)
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = A.dot(A).dot(A).dot(B)
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[  -6.   42.]
 [ -18.  111.]
 [ 144. -507.]
 [ 134. -534.]]


A * A * B = 
[[  -72.   414.]
 [ -162.   909.]
 [   66.   -81.]
 [  248. -1122.]]


A * A * A * B = 
[[ -540.  2970.]
 [-1134.  6183.]
 [ -438.  2637.]
 [  860. -4326.]]


In [8]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

{A,B} = 
     0    1      2      3      4       5       6       7
0  1.0 -2.0   -6.0   42.0  -72.0   414.0  -540.0  2970.0
1  0.0  5.0  -18.0  111.0 -162.0   909.0 -1134.0  6183.0
2  7.0 -9.0  144.0 -507.0   66.0   -81.0  -438.0  2637.0
3  0.0  2.0  134.0 -534.0  248.0 -1122.0   860.0 -4326.0


In [9]:
rang_beta = np.linalg.matrix_rank(beta)
print("Ранг матрицы управляемости rg {A,B} = " + str(rang_beta))

Ранг матрицы управляемости rg {A,B} = 4


In [10]:
#проверка для 1.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[ -6.]
 [-18.]
 [144.]
 [134.]]


A * A * B_1 = 
[[ -72.]
 [-162.]
 [  66.]
 [ 248.]]


A * A * A * B_1 = 
[[ -540.]
 [-1134.]
 [ -438.]
 [  860.]]


In [ ]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0      1      2       3
0  1.0   -6.0  -72.0  -540.0
1  0.0  -18.0 -162.0 -1134.0
2  7.0  144.0   66.0  -438.0
3  0.0  134.0  248.0   860.0

Ранг матрицы управляемости rg {A,B_1} = 4


In [11]:
#дополнительные вычисления для матрицы наблюдаемости
A_arr = A.T
C_arr = C.T

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print("A * C = ")
print(AC)
print('\n')

print("A * A * C = ")
print(AAC)
print('\n')
print("A * A * A * C = ")
print(AAAC)
print('\n')

A * C = 
[[ 201.]
 [-156.]
 [   9.]
 [ -12.]]


A * A * C = 
[[1227.]
 [-894.]
 [   9.]
 [ -12.]]


A * A * A * C = 
[[ 8355.]
 [-5808.]
 [    9.]
 [  -12.]]




In [12]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print('{A, С} = ')
print(pd.DataFrame(gamma))
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C} = " + str(rang_gamma))

{A, С} = 
     0      1       2       3
0 -8.0  201.0  1227.0  8355.0
1 -4.0 -156.0  -894.0 -5808.0
2  1.0    9.0     9.0     9.0
3  0.0  -12.0   -12.0   -12.0

Ранг матрицы наблюдаемости rg {A,C} = 4


In [13]:
#пункт 1.15
#1) дополнительные вычисления (в методичке описаны пунктом 1.2.2)
I = np.eye(4)
print("D_0 = ")
D0 = I
print(D0)
print('\n')

d1 = np.round(-np.trace(D0.dot(A)))
print("d_1 = " + str(d1))
print("D_1 = ")
D1 = D0 + d1 * I
print(D1)
print('\n')

d2 = np.round(-(1.0/2) * np.trace(D1.dot(A)))
print("d_2 = " + str(d2))
print("D_2 = ")
D2 = D1 + d2 * I
print(D2)
print('\n')


d3 = np.round(-(1.0/3) * np.trace(D2.dot(A)))
print("d_3 = " + str(d3))
print("D_3 = ")
D3 = D2 + d3 * I
print(D3)
print('\n')

d4 = np.round(-(1.0/4) * np.trace(D3.dot(A)))
print("d_4 = " + str(d4))
print('\n')

#почему-то не работает проверка... (она должна вывести 0)
check = D3.dot(A) + d4 * I
print(check)

D_0 = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


d_1 = -10.0
D_1 = 
[[-9.  0.  0.  0.]
 [ 0. -9.  0.  0.]
 [ 0.  0. -9.  0.]
 [ 0.  0.  0. -9.]]


d_2 = 45.0
D_2 = 
[[36.  0.  0.  0.]
 [ 0. 36.  0.  0.]
 [ 0.  0. 36.  0.]
 [ 0.  0.  0. 36.]]


d_3 = -120.0
D_3 = 
[[-84.   0.   0.   0.]
 [  0. -84.   0.   0.]
 [  0.   0. -84.   0.]
 [  0.   0.   0. -84.]]


d_4 = 210.0


[[  714.  -504.     0.     0.]
 [ 1512. -1050.     0.     0.]
 [-6804.  4032.  -546.  1008.]
 [-7728.  4704.  -504.   882.]]


In [14]:
#нахождение матрицы S
S4 = B[:,0]
S3 = A.dot(S4) + d1 * B[:,0]
S2 = A.dot(S3) + d2 * B[:,0]
S1 = A.dot(S2) + d3 * B[:,0]
print('S_1 = ')
print(S1)
print('\nS_2 = ')
print(S2)
print('\nS_3 = ')
print(S3)
print('\nS_4 = ')
print(S4)
print('\nS = ')
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))
print('\nS_ = ')
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_))

S_1 = 
[[-210.]
 [-324.]
 [4542.]
 [4410.]]

S_2 = 
[[   33.]
 [   18.]
 [-1059.]
 [-1092.]]

S_3 = 
[[-16.]
 [-18.]
 [ 74.]
 [134.]]

S_4 = 
[[1]
 [0]
 [7]
 [0]]

S = 
        0       1      2    3
0  -210.0    33.0  -16.0  1.0
1  -324.0    18.0  -18.0  0.0
2  4542.0 -1059.0   74.0  7.0
3  4410.0 -1092.0  134.0  0.0

S_ = 
          0         1         2         3
0 -0.019364  0.004853  0.002766 -0.003188
1 -0.040385  0.002350  0.005769 -0.007692
2  0.308160 -0.140558 -0.044023  0.049688
3  3.196899 -1.307375 -0.313843  0.379418


In [ ]:
#в пункте 2) надо самому разложить многочлен по примеру и коэффициенты при p будут равны соответствующим позициям для вектора d с чертой

In [15]:
#3-4) поиск матрицы K
K_ = np.matrix([-219, 124, -39, 14]) #это K с чертой (ее можно найти с помощью пункта 2)
K = K_.dot(S_)
print("K = ")
print(K)

K = 
[[ 31.97127512 -13.59282744  -2.56732502   3.11829522]]


In [16]:
#5) поиск A с чертой
A_ = A - (B[:,0]).dot(K)
print('A_ = ')
print(A_)

A_ = 
[[ -37.97127512   19.59282744    2.56732502   -3.11829522]
 [ -18.           15.            0.            0.        ]
 [-142.79892585   47.1497921    26.97127512  -33.82806653]
 [  92.          -56.            6.           -8.        ]]
