<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import pandas as pd
import numpy as np

In [40]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, -6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[1,1,0,3],[3,2,0,1],[1,0,3,4],[0,1,0,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2], [0, 5],[7, -9],[0, 2]])
C = np.matrix([-8, -4, 1, 0])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[ 3  0  0  0]
 [ 0 -6  0  0]
 [ 0  0  1  0]
 [ 0  0  0  1]]
L = 
[[1 1 0 3]
 [3 2 0 1]
 [1 0 3 4]
 [0 1 0 3]]
B = 
[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
C = 
[[-8 -4  1  0]]


In [41]:
print('det(L) = ' + str(np.linalg.det(L)))

det(L) = 15.000000000000007


In [42]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[ 1.          0.          0.         -1.        ]
 [-1.8         0.6         0.          1.6       ]
 [-1.13333333  0.26666667  0.33333333  0.6       ]
 [ 0.6        -0.2         0.         -0.2       ]]


In [43]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(A)

A = 
[[ 1.56000000e+01 -4.20000000e+00  0.00000000e+00 -1.32000000e+01]
 [ 3.12000000e+01 -7.40000000e+00  0.00000000e+00 -2.84000000e+01]
 [ 2.00000000e+00  1.11022302e-16  1.00000000e+00 -2.00000000e+00]
 [ 1.26000000e+01 -4.20000000e+00  0.00000000e+00 -1.02000000e+01]]


In [45]:
#дополнительные вычисления для составления матрицы управляемости

AB = A.dot(B)
print("A * B = ")
print(AB)
print("\n")

AAB = A.dot(A).dot(B)
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = A.dot(A).dot(A).dot(B)
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[  15.6  -78.6]
 [  31.2 -156.2]
 [   9.   -17. ]
 [  12.6  -66.6]]


A * A * B = 
[[ -54.  309.]
 [-102.  595.]
 [  15.  -41.]
 [ -63.  345.]]


A * A * A * B = 
[[  417.6 -2232.6]
 [  859.2 -4560.2]
 [   33.   -113. ]
 [  390.6 -2124.6]]


In [46]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

{A,B} = 
     0    1     2      3      4      5      6       7
0  1.0 -2.0  16.0  -79.0  -54.0  309.0  418.0 -2233.0
1  0.0  5.0  31.0 -156.0 -102.0  595.0  859.0 -4560.0
2  7.0 -9.0   9.0  -17.0   15.0  -41.0   33.0  -113.0
3  0.0  2.0  13.0  -67.0  -63.0  345.0  391.0 -2125.0


In [47]:
rang_beta = np.linalg.matrix_rank(beta)
print("Ранг матрицы управляемости rg {A,B} = " + str(rang_beta))

Ранг матрицы управляемости rg {A,B} = 4


In [48]:
#проверка для 1.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[15.6]
 [31.2]
 [ 9. ]
 [12.6]]


A * A * B_1 = 
[[ -54.]
 [-102.]
 [  15.]
 [ -63.]]


A * A * A * B_1 = 
[[417.6]
 [859.2]
 [ 33. ]
 [390.6]]


In [49]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0     1      2      3
0  1.0  15.6  -54.0  417.6
1  0.0  31.2 -102.0  859.2
2  7.0   9.0   15.0   33.0
3  0.0  12.6  -63.0  390.6

Ранг матрицы управляемости rg {A,B_1} = 3


In [50]:
#дополнительные вычисления для матрицы наблюдаемости
A_arr = A.T
C_arr = C.T

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print("A * C = ")
print(AC)
print('\n')

print("A * A * C = ")
print(AAC)
print('\n')
print("A * A * A * C = ")
print(AAAC)
print('\n')

A * C = 
[[-247.6]
 [  63.2]
 [   1. ]
 [ 217.2]]


A * A * C = 
[[ 848.]
 [-340.]
 [   1.]
 [-744.]]


A * A * A * C = 
[[-6.7516e+03]
 [ 2.0792e+03]
 [ 1.0000e+00]
 [ 6.0492e+03]]




In [51]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print('{A, С} = ')
print(pd.DataFrame(gamma))
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C} = " + str(rang_gamma))

{A, С} = 
     0      1      2       3
0 -8.0 -247.6  848.0 -6751.6
1 -4.0   63.2 -340.0  2079.2
2  1.0    1.0    1.0     1.0
3  0.0  217.2 -744.0  6049.2

Ранг матрицы наблюдаемости rg {A,C} = 3


In [53]:
#пункт 1.15
#1) дополнительные вычисления (в методичке описаны пунктом 1.2.2)
I = np.eye(4)
print("D_0 = ")
D0 = I
print(D0)
print('\n')

d1 = -np.trace(D0.dot(A))
print("d_1 = " + str(d1))
print("D_1 = ")
D1 = D0 + (I.dot(d1))
print(D1)
print('\n')

d2 = -0.5 * np.trace(D1.dot(A))
print("d_2 = " + str(d2))
print("D_2 = ")
D2 = D1 + (I.dot(d2))
print(D2)
print('\n')


d3 = -(1.0/3.0) * np.trace(D2.dot(A))
print("d_3 = " + str(d3))
print("D_3 = ")
D3 = D2 + (I.dot(d3))
print(D3)
print('\n')

d4 = -0.25 * np.trace(D3.dot(A))
print("d_4 = " + str(d4))
print('\n')

#почему-то не работает проверка... (она должна вывести 0)
check = D3.dot(A) + (I.dot(d4))
print(np.round(check))

D_0 = 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


d_1 = 1.0000000000000018
D_1 = 
[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


d_2 = 1.0000000000000036
D_2 = 
[[3. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 3.]]


d_3 = 1.0000000000000047
D_3 = 
[[4. 0. 0. 0.]
 [0. 4. 0. 0.]
 [0. 0. 4. 0.]
 [0. 0. 0. 4.]]


d_4 = 1.000000000000007


[[  63.  -17.    0.  -53.]
 [ 125.  -29.    0. -114.]
 [   8.    0.    5.   -8.]
 [  50.  -17.    0.  -40.]]


In [16]:
#нахождение матрицы S
S4 = B[:,0]
S3 = A.dot(S4) + d1 * B[:,0]
S2 = A.dot(S3) + d2 * B[:,0]
S1 = A.dot(S2) + d3 * B[:,0]
print('S_1 = ')
print(S1)
print('\nS_2 = ')
print(S2)
print('\nS_3 = ')
print(S3)
print('\nS_4 = ')
print(S4)
print('\nS = ')
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))
print('\nS_ = ')
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_))

S_1 = 
[[-210.]
 [-324.]
 [4542.]
 [4410.]]

S_2 = 
[[   33.]
 [   18.]
 [-1059.]
 [-1092.]]

S_3 = 
[[-16.]
 [-18.]
 [ 74.]
 [134.]]

S_4 = 
[[1]
 [0]
 [7]
 [0]]

S = 
        0       1      2    3
0  -210.0    33.0  -16.0  1.0
1  -324.0    18.0  -18.0  0.0
2  4542.0 -1059.0   74.0  7.0
3  4410.0 -1092.0  134.0  0.0

S_ = 
          0         1         2         3
0 -0.019364  0.004853  0.002766 -0.003188
1 -0.040385  0.002350  0.005769 -0.007692
2  0.308160 -0.140558 -0.044023  0.049688
3  3.196899 -1.307375 -0.313843  0.379418


In [18]:
print('det(S) = ' + str(np.linalg.det(S)) + ' не равно 0')

det(S) = -6233759.999999989 не равно 0


In [ ]:
#в пункте 2) надо самому разложить многочлен по примеру и коэффициенты при p будут равны соответствующим позициям для вектора d с чертой

In [ ]:
#3-4) поиск матрицы K
K_ = np.matrix([-219, 124, -39, 14]) #это K с чертой (ее можно найти с помощью пункта 2)
K = K_.dot(S_)
print("K = ")
print(K)

K = 
[[ 31.97127512 -13.59282744  -2.56732502   3.11829522]]


In [ ]:
#5) поиск A с чертой
A_ = A - (B[:,0]).dot(K)
print('A_ = ')
print(A_)

A_ = 
[[ -37.97127512   19.59282744    2.56732502   -3.11829522]
 [ -18.           15.            0.            0.        ]
 [-142.79892585   47.1497921    26.97127512  -33.82806653]
 [  92.          -56.            6.           -8.        ]]
