<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab1_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[3, 0, 0, 0], [0, 6, 0, 0], [0, 0, 1, 0], [0, 0, 0, 0]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2], [0, 5],[7, -9],[0, 2]])
C = np.matrix([-8, -4, 1, 0])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[3 0 0 0]
 [0 6 0 0]
 [0 0 1 0]
 [0 0 0 0]]
L = 
[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
B = 
[[ 1 -2]
 [ 0  5]
 [ 7 -9]
 [ 0  2]]
C = 
[[-8 -4  1  0]]


In [3]:
print('det(L) = ' + str(np.linalg.det(L)))

det(L) = 0.9999999999999991


In [4]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [5]:
print("L * L_обр = ")
print(pd.DataFrame(np.round(L.dot(L_))))

L * L_обр = 
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0 -0.0  1.0  0.0
3  0.0  0.0 -0.0  1.0


In [6]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(np.round(A))

A = 
[[ -6.   6.   0.   0.]
 [-18.  15.   0.   0.]
 [ 81. -48.   9. -12.]
 [ 92. -56.   6.  -8.]]


In [7]:
#дополнительные вычисления для составления матрицы управляемости

AB = A.dot(B)
print("A * B = ")
print(AB)
print("\n")

AAB = A.dot(A).dot(B)
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = A.dot(A).dot(A).dot(B)
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[  -6.   42.]
 [ -18.  111.]
 [ 144. -507.]
 [ 134. -534.]]


A * A * B = 
[[  -72.   414.]
 [ -162.   909.]
 [   66.   -81.]
 [  248. -1122.]]


A * A * A * B = 
[[ -540.  2970.]
 [-1134.  6183.]
 [ -438.  2637.]
 [  860. -4326.]]


In [8]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

{A,B} = 
     0    1      2      3      4       5       6       7
0  1.0 -2.0   -6.0   42.0  -72.0   414.0  -540.0  2970.0
1  0.0  5.0  -18.0  111.0 -162.0   909.0 -1134.0  6183.0
2  7.0 -9.0  144.0 -507.0   66.0   -81.0  -438.0  2637.0
3  0.0  2.0  134.0 -534.0  248.0 -1122.0   860.0 -4326.0


In [9]:
rang_beta = np.linalg.matrix_rank(beta)
print("Ранг матрицы управляемости rg {A,B} = " + str(rang_beta))

Ранг матрицы управляемости rg {A,B} = 4


In [10]:
#проверка для 1.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[ -6.]
 [-18.]
 [144.]
 [134.]]


A * A * B_1 = 
[[ -72.]
 [-162.]
 [  66.]
 [ 248.]]


A * A * A * B_1 = 
[[ -540.]
 [-1134.]
 [ -438.]
 [  860.]]


In [11]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0      1      2       3
0  1.0   -6.0  -72.0  -540.0
1  0.0  -18.0 -162.0 -1134.0
2  7.0  144.0   66.0  -438.0
3  0.0  134.0  248.0   860.0

Ранг матрицы управляемости rg {A,B_1} = 4


In [12]:
#дополнительные вычисления для матрицы наблюдаемости
A_arr = A.T
C_arr = C.T

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print("A * C = ")
print(AC)
print('\n')

print("A * A * C = ")
print(AAC)
print('\n')
print("A * A * A * C = ")
print(AAAC)
print('\n')

A * C = 
[[ 201.]
 [-156.]
 [   9.]
 [ -12.]]


A * A * C = 
[[1227.]
 [-894.]
 [   9.]
 [ -12.]]


A * A * A * C = 
[[ 8355.]
 [-5808.]
 [    9.]
 [  -12.]]




In [15]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print('{A, С} = ')
print(pd.DataFrame(gamma))
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C} = " + str(rang_gamma))

{A, С} = 
     0      1       2       3
0 -8.0  201.0  1227.0  8355.0
1 -4.0 -156.0  -894.0 -5808.0
2  1.0    9.0     9.0     9.0
3  0.0  -12.0   -12.0   -12.0

Ранг матрицы наблюдаемости rg {A,C} = 4


In [17]:
#пункт 1.15
#1) 
d0 = 1
d1 = -10
d2 = 27
d3 = -18

In [40]:
#нахождение матрицы S
S4 = np.round(B[:,0])
S3 = np.round(A.dot(S4) + d1 * B[:,0])
S2 = np.round(A.dot(S3) + d2 * B[:,0])
S1 = np.round(A.dot(S2) + d3 * B[:,0])
print('S_1 = ')
print(S1)
print('\nS_2 = ')
print(S2)
print('\nS_3 = ')
print(S3)
print('\nS_4 = ')
print(S4)
print('\nS = ')
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))
print('\nS_обр = 1/6233760 *')
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_ * 6233760))

S_1 = 
[[  -0.]
 [  -0.]
 [2664.]
 [1998.]]

S_2 = 
[[   15.]
 [   18.]
 [-1185.]
 [-1092.]]

S_3 = 
[[-16.]
 [-18.]
 [ 74.]
 [134.]]

S_4 = 
[[1]
 [0]
 [7]
 [0]]

S = 
        0       1      2    3
0    -0.0    15.0  -16.0  1.0
1    -0.0    18.0  -18.0  0.0
2  2664.0 -1185.0   74.0  7.0
3  1998.0 -1092.0  134.0  0.0

S_обр = 1/6233760 *
           0          1        2        3
0  -120708.0    30252.0  17244.0 -19872.0
1  -251748.0    14652.0  35964.0 -47952.0
2  -251748.0  -331668.0  35964.0 -47952.0
3  5982012.0 -5526468.0  35964.0 -47952.0


In [41]:
print("S * S_обр = ")
pd.DataFrame(np.round(S.dot(S_)))

S * S_обр = 


0    1    2    3
0  1.0  0.0 -0.0  0.0
1  0.0  1.0 -0.0  0.0
2 -0.0 -0.0  1.0 -0.0
3 -0.0 -0.0 -0.0  1.0

In [42]:
print('det(S) = ' + str(np.round(np.linalg.det(S))))

det(S) = -6233760.0


In [ ]:
#в пункте 2) надо самому разложить многочлен по примеру и коэффициенты при p будут равны соответствующим позициям для вектора d с чертой

In [43]:
#3-4) поиск матрицы K
d_ = [-2, -53, 198, -144]
d = [-10, 27, -18, 0]
K_ = np.matrix([d_[3] - d[3], d_[2] - d[2], d_[1] - d[1], d_[0] - d[0]]) #это K с чертой (ее можно найти с помощью пункта 2)
#print(K_)
K = K_.dot(S_)
print("K = 1/6233760 * ")
print(K*6233760.0)

K = 1/6233760 * 
[[ 31000320. -18869760.   2695680.  -4043520.]]


In [44]:
#5) поиск A с чертой
A_ = A - (B[:,0]).dot(K)
print('A_ = 1/6233760 * ')
print(pd.DataFrame(A_*6233760))

A_ = 1/6233760 * 
              0            1           2           3
0 -6.840288e+07   56272320.0  -2695680.0   4043520.0
1 -1.122077e+08   93506400.0         0.0         0.0
2  2.879323e+08 -167132160.0  37234080.0 -46500480.0
3  5.735059e+08 -349090560.0  37402560.0 -49870080.0


In [56]:
lambda1 = -8
I = np.eye(4)
check1 = lambda1 * I - A_
print('lambda * I - A_ = 1/6233760 * \n' + str(pd.DataFrame(check1*6233760)))
print('\ndet (lambda * I - A_) = ' + str(np.round(np.linalg.det(check1))))

lambda * I - A_ = 1/6233760 * 
              0            1           2             3
0  1.853280e+07  -56272320.0   2695680.0 -4.043520e+06
1  1.122077e+08 -143376480.0         0.0  0.000000e+00
2 -2.879323e+08  167132160.0 -87104160.0  4.650048e+07
3 -5.735059e+08  349090560.0 -37402560.0  3.322015e-08

det (lambda * I - A_) = -0.0


In [57]:
lambda2 = 1
check2 = lambda2 * I - A_
print('lambda * I - A_ = 1/6233760 * \n' + str(pd.DataFrame(check2*6233760)))
print('\ndet (lambda * I - A_) = ' + str((np.round(np.linalg.det(check2)))))

lambda * I - A_ = 1/6233760 * 
              0            1           2           3
0  7.463664e+07  -56272320.0   2695680.0  -4043520.0
1  1.122077e+08  -87272640.0         0.0         0.0
2 -2.879323e+08  167132160.0 -31000320.0  46500480.0
3 -5.735059e+08  349090560.0 -37402560.0  56103840.0

det (lambda * I - A_) = 0.0


In [58]:
lambda3 = 3
check3 = lambda3 * I - A_
print('lambda * I - A_ = 1/6233760 * \n' + str(pd.DataFrame(check3*6233760)))
print('\ndet (lambda * I - A_) = ' + str(np.round((np.linalg.det(check3)))))

lambda * I - A_ = 1/6233760 * 
              0            1           2           3
0  8.710416e+07  -56272320.0   2695680.0  -4043520.0
1  1.122077e+08  -74805120.0         0.0         0.0
2 -2.879323e+08  167132160.0 -18532800.0  46500480.0
3 -5.735059e+08  349090560.0 -37402560.0  68571360.0

det (lambda * I - A_) = 0.0


In [59]:
lambda4 = 6
check4 = lambda4 * I - A_
print('lambda * I - A_ = 1/6233760 * \n' + str(pd.DataFrame(check4*6233760)))
print('\ndet (lambda * I - A_) = ' + str((np.round(np.linalg.det(check4)))))

lambda * I - A_ = 1/6233760 * 
              0            1           2           3
0  1.058054e+08  -56272320.0   2695680.0  -4043520.0
1  1.122077e+08  -56103840.0         0.0         0.0
2 -2.879323e+08  167132160.0    168480.0  46500480.0
3 -5.735059e+08  349090560.0 -37402560.0  87272640.0

det (lambda * I - A_) = 0.0
