<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab2_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#2.11

In [2]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[28, 0, 0, 0], [0, -2, 0, 0], [0, 0, 1, 0], [0, 0, 0, 11]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2, 43], [0, 5, -9],[7, -9, 11],[0, 2, 8]])
C = np.matrix([[-8, -4, 51, 31], [1, 0, 71, 5]])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[28  0  0  0]
 [ 0 -2  0  0]
 [ 0  0  1  0]
 [ 0  0  0 11]]
L = 
[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
B = 
[[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]
C = 
[[-8 -4 51 31]
 [ 1  0 71  5]]


In [3]:
print('det(L) = ' + str(np.linalg.det(L)))

det(L) = 0.9999999999999991


In [4]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [5]:
print("L * L_обр = ")
print(pd.DataFrame(np.round(L.dot(L_))))

L * L_обр = 
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0 -0.0  1.0  0.0
3  0.0  0.0 -0.0  1.0


In [6]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(np.round(A))

A = 
[[ 118.  -60.    0.    0.]
 [ 180.  -92.    0.    0.]
 [-857.  527.  -79.  120.]
 [-591.  372.  -60.   91.]]


#2.12

In [7]:
#дополнительные вычисления для составления матрицы управляемости

AB = np.round(A.dot(B))
print("A * B = ")
print(AB)
print("\n")

AAB = np.round(A.dot(A).dot(B))
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = np.round(A.dot(A).dot(A).dot(B))
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[   118.   -536.   5614.]
 [   180.   -820.   8568.]
 [ -1410.   5300. -41503.]
 [ -1011.   3764. -28693.]]


A * A * B = 
[[   3124.  -14048.  148372.]
 [   4680.  -21040.  222264.]
 [ -16196.   60192. -460285.]
 [ -10179.   36260. -251461.]]


A * A * A * B = 
[[   87832.  -395264.  4172056.]
 [  131760.  -592960.  6258672.]
 [ -152904.   547088. -3834481.]
 [  -59853.   163628.  -271495.]]


In [8]:
# Сброс ограничений на количество выводимых рядов
pd.set_option('display.max_rows', None)
# Сброс ограничений на число столбцов
pd.set_option('display.max_columns', None)
# Сброс ограничений на количество символов в записи
pd.set_option('display.max_colwidth', None)

In [9]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))

{A,B} = 
    0    1     2       3       4        5        6        7         8   \
0  1.0 -2.0  43.0   118.0  -536.0   5614.0   3124.0 -14048.0  148372.0   
1  0.0  5.0  -9.0   180.0  -820.0   8568.0   4680.0 -21040.0  222264.0   
2  7.0 -9.0  11.0 -1410.0  5300.0 -41503.0 -16196.0  60192.0 -460285.0   
3  0.0  2.0   8.0 -1011.0  3764.0 -28693.0 -10179.0  36260.0 -251461.0   

         9         10         11  
0   87832.0 -395264.0  4172056.0  
1  131760.0 -592960.0  6258672.0  
2 -152904.0  547088.0 -3834481.0  
3  -59853.0  163628.0  -271495.0  

Ранг матрицы управляемости rg {A,B} = 4


In [10]:
#проверка для 2.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[  118.]
 [  180.]
 [-1410.]
 [-1011.]]


A * A * B_1 = 
[[  3124.]
 [  4680.]
 [-16196.]
 [-10179.]]


A * A * A * B_1 = 
[[  87832.]
 [ 131760.]
 [-152904.]
 [ -59853.]]


In [11]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0       1        2         3
0  1.0   118.0   3124.0   87832.0
1  0.0   180.0   4680.0  131760.0
2  7.0 -1410.0 -16196.0 -152904.0
3  0.0 -1011.0 -10179.0  -59853.0

Ранг матрицы управляемости rg {A,B_1} = 4


In [33]:
def Fadeev(A_T_A, F, mu, A_T):
    I = np.diag(np.diag(np.ones([3,3])))
    i = 2
    while mu != 0.0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0.0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("\nШаг", i-1)
        print("F:\n", F)
        print("\nA_T_A * F:\n", A_T_A.dot(F))
        print("mu\n", mu)
        print("\n")
        
        i+=1
        
    return(_F.dot(A_T), _mu)

In [34]:
B_T = B.transpose()
B_T_B = B_T.dot(B) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([3,3]))) #единичная матрица
mu = sum(np.diag(B_T_B)) #это фи1 (сумма значений матрицы B_T_B по диагонали)
print("B =\n", B)
print("B^T * B =\n", B_T_B)
print("mu_0 =\n", mu)
print("F_0 =\n", F)

B_, coef_ = Fadeev(B_T_B, F, mu, B_T)
print("1/" + str(coef_) + " * B_обр:\n" + str(B_))

B =
 [[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]
B^T * B =
 [[  50  -65  120]
 [ -65  114 -214]
 [ 120 -214 2115]]
mu_0 =
 2279
F_0 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Шаг 1
F:
 [[2229.   65. -120.]
 [  65. 2165.  214.]
 [-120.  214.  164.]]

A_T_A * F:
 [[ 9.28250e+04 -1.11795e+05 -2.30000e+02]
 [-1.11795e+05  1.96789e+05 -2.90000e+03]
 [-2.30000e+02 -2.90000e+03  2.86664e+05]]
mu
 288139.0



Шаг 2
F:
 [[195314. 111795.    230.]
 [111795.  91350.   2900.]
 [   230.   2900.   1475.]]

A_T_A * F:
 [[2526625.       0.       0.]
 [      0. 2526625.       0.]
 [      0.       0. 2526625.]]
mu
 2526625.0



Шаг 3
F:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A_T_A * F:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
mu
 0.0


1/2526625.0 * B_обр:
[[-18386. 556905. 363573. 225430.]
 [ 53795. 430650.  -7685. 205900.]
 [ 57855.   1225.  -8265.  17600.]]


In [37]:
print("По свойству псевдообратной матрицы, где В*B_обр*В=B,\n = \nВ * B_обр * В =")
print(np.round(B.dot(B_/coef_).dot(B)))

print("B = \n", B)

По свойству псевдообратной матрицы, где В*B_обр*В=B,
 = 
В * B_обр * В =
[[ 1. -2. 43.]
 [-0.  5. -9.]
 [ 7. -9. 11.]
 [ 0.  2.  8.]]
B = 
 [[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]


In [44]:
print("B * B_обр = 1/" + str(coef_) + "\n" + str(B.dot(B_)))
BB_ = B.dot(B_/coef_)

B * B_обр = 1/2526625.0
[[2361789. -251720.   23548.  570430.]
 [-251720. 2142225.   35960.  871100.]
 [  23548.   35960. 2523261.  -81490.]
 [ 570430.  871100.  -81490.  552600.]]
