<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab2_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

#2.11

In [2]:
#Матрица собственных чисел:
print('lambda = ')
lambda_matrix = np.matrix([[28, 0, 0, 0], [0, -2, 0, 0], [0, 0, 1, 0], [0, 0, 0, 11]])
print(lambda_matrix)
#обратимая матрица
L = np.matrix([[2,1,0,0],[3,2,0,0],[1,1,3,4],[2,-1,2,3]])
print('L = ')
print(L)
#также даны:
B = np.matrix([[1, -2, 43], [0, 5, -9],[7, -9, 11],[0, 2, 8]])
C = np.matrix([[-8, -4, 51, 31], [1, 0, 71, 5]])
print('B = ')
print(B)
print('C = ')
print(C)

lambda = 
[[28  0  0  0]
 [ 0 -2  0  0]
 [ 0  0  1  0]
 [ 0  0  0 11]]
L = 
[[ 2  1  0  0]
 [ 3  2  0  0]
 [ 1  1  3  4]
 [ 2 -1  2  3]]
B = 
[[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]
C = 
[[-8 -4 51 31]
 [ 1  0 71  5]]


In [3]:
print('det(L) = ' + str(np.linalg.det(L)))

det(L) = 0.9999999999999991


In [4]:
#обратная матрица от обратимой
L_ = np.linalg.inv(L)
print('L_обр = ')
print(L_)

L_обр = 
[[  2.  -1.   0.   0.]
 [ -3.   2.  -0.  -0.]
 [ 31. -19.   3.  -4.]
 [-23.  14.  -2.   3.]]


In [5]:
print("L * L_обр = ")
print(pd.DataFrame(np.round(L.dot(L_))))

L * L_обр = 
     0    1    2    3
0  1.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0
2  0.0 -0.0  1.0  0.0
3  0.0  0.0 -0.0  1.0


In [6]:
#исходная матрица
A = L.dot(lambda_matrix).dot(L_)
print('A = ')
print(np.round(A))

A = 
[[ 118.  -60.    0.    0.]
 [ 180.  -92.    0.    0.]
 [-857.  527.  -79.  120.]
 [-591.  372.  -60.   91.]]


#2.12

In [7]:
#дополнительные вычисления для составления матрицы управляемости

AB = np.round(A.dot(B))
print("A * B = ")
print(AB)
print("\n")

AAB = np.round(A.dot(A).dot(B))
print("A * A * B = ")
print(AAB)
print("\n")

AAAB = np.round(A.dot(A).dot(A).dot(B))
print("A * A * A * B = ")
print(AAAB)

A * B = 
[[   118.   -536.   5614.]
 [   180.   -820.   8568.]
 [ -1410.   5300. -41503.]
 [ -1011.   3764. -28693.]]


A * A * B = 
[[   3124.  -14048.  148372.]
 [   4680.  -21040.  222264.]
 [ -16196.   60192. -460285.]
 [ -10179.   36260. -251461.]]


A * A * A * B = 
[[   87832.  -395264.  4172056.]
 [  131760.  -592960.  6258672.]
 [ -152904.   547088. -3834481.]
 [  -59853.   163628.  -271495.]]


In [ ]:
# Сброс ограничений на количество выводимых рядов
pd.set_option('display.max_rows', None)
# Сброс ограничений на число столбцов
pd.set_option('display.max_columns', None)
# Сброс ограничений на количество символов в записи
pd.set_option('display.max_colwidth', None)

In [8]:
#матрица управляемости
beta = np.concatenate((np.round(B), np.round(AB), np.round(AAB), np.round(AAAB)), axis=1)
print("{A,B} = ")
print(pd.DataFrame(beta))

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))

{A,B} = 
    0    1     2       3       4        5        6        7         8   \
0  1.0 -2.0  43.0   118.0  -536.0   5614.0   3124.0 -14048.0  148372.0   
1  0.0  5.0  -9.0   180.0  -820.0   8568.0   4680.0 -21040.0  222264.0   
2  7.0 -9.0  11.0 -1410.0  5300.0 -41503.0 -16196.0  60192.0 -460285.0   
3  0.0  2.0   8.0 -1011.0  3764.0 -28693.0 -10179.0  36260.0 -251461.0   

         9         10         11  
0   87832.0 -395264.0  4172056.0  
1  131760.0 -592960.0  6258672.0  
2 -152904.0  547088.0 -3834481.0  
3  -59853.0  163628.0  -271495.0  

Ранг матрицы управляемости rg {A,B} = 4


In [9]:
#проверка для 2.15
print("B_1 = ")
print(B[:,0])
print('\n')

print('A * B_1 = ')
AB1 = A.dot(B[:,0])
print(AB1)
print('\n')

AAB1 = A.dot(A).dot(B[:,0])
print('A * A * B_1 = ')
print(AAB1)
print('\n')

print('A * A * A * B_1 = ')
AAAB1 = A.dot(A).dot(A).dot(B[:,0])
print(AAAB1)

B_1 = 
[[1]
 [0]
 [7]
 [0]]


A * B_1 = 
[[  118.]
 [  180.]
 [-1410.]
 [-1011.]]


A * A * B_1 = 
[[  3124.]
 [  4680.]
 [-16196.]
 [-10179.]]


A * A * A * B_1 = 
[[  87832.]
 [ 131760.]
 [-152904.]
 [ -59853.]]


In [10]:
beta1 = np.concatenate((B[:,0], AB1, AAB1, AAAB1), axis=1)
print('{A, B_1} = ')
print(pd.DataFrame(beta1))
rang_beta1 = np.linalg.matrix_rank(beta1)
print("\nРанг матрицы управляемости rg {A,B_1} = " + str(rang_beta1))

{A, B_1} = 
     0       1        2         3
0  1.0   118.0   3124.0   87832.0
1  0.0   180.0   4680.0  131760.0
2  7.0 -1410.0 -16196.0 -152904.0
3  0.0 -1011.0 -10179.0  -59853.0

Ранг матрицы управляемости rg {A,B_1} = 4


##2.12.2

In [ ]:
def Fadeev(A_T_A, F, mu, A_T):
    I = np.diag(np.diag(np.ones([3,3])))
    i = 2
    while mu != 0.0:
        if sum(np.diag(A_T_A.dot(mu*I - A_T_A.dot(F))))/float(i) == 0.0:
            _mu = mu
            _F = F
        F = mu*I - A_T_A.dot(F)
        mu = sum(np.diag(A_T_A.dot(F)))/float(i)
        
        print("\nШаг", i-1)
        print("F:\n", F)
        print("\nA_T_A * F:\n", A_T_A.dot(F))
        print("mu\n", mu)
        print("\n")
        
        i+=1
        
    return(_F.dot(A_T), _mu)

In [ ]:
B_T = B.transpose()
B_T_B = B_T.dot(B) #перемножены транспонированная матрица и обычная
F = np.diag(np.diag(np.ones([3,3]))) #единичная матрица
mu = sum(np.diag(B_T_B)) #это фи1 (сумма значений матрицы B_T_B по диагонали)
print("B =\n", B)
print("B^T * B =\n", B_T_B)
print("mu_0 =\n", mu)
print("F_0 =\n", F)

B_, coef_ = Fadeev(B_T_B, F, mu, B_T)
print("1/" + str(coef_) + " * B_обр:\n" + str(B_))

B =
 [[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]
B^T * B =
 [[  50  -65  120]
 [ -65  114 -214]
 [ 120 -214 2115]]
mu_0 =
 2279
F_0 =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Шаг 1
F:
 [[2229.   65. -120.]
 [  65. 2165.  214.]
 [-120.  214.  164.]]

A_T_A * F:
 [[ 9.28250e+04 -1.11795e+05 -2.30000e+02]
 [-1.11795e+05  1.96789e+05 -2.90000e+03]
 [-2.30000e+02 -2.90000e+03  2.86664e+05]]
mu
 288139.0



Шаг 2
F:
 [[195314. 111795.    230.]
 [111795.  91350.   2900.]
 [   230.   2900.   1475.]]

A_T_A * F:
 [[2526625.       0.       0.]
 [      0. 2526625.       0.]
 [      0.       0. 2526625.]]
mu
 2526625.0



Шаг 3
F:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

A_T_A * F:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
mu
 0.0


1/2526625.0 * B_обр:
[[-18386. 556905. 363573. 225430.]
 [ 53795. 430650.  -7685. 205900.]
 [ 57855.   1225.  -8265.  17600.]]


In [ ]:
print("По свойству псевдообратной матрицы, где В*B_обр*В=B,\n = \nВ * B_обр * В =")
print(np.round(B.dot(B_/coef_).dot(B)))

print("B = \n", B)

По свойству псевдообратной матрицы, где В*B_обр*В=B,
 = 
В * B_обр * В =
[[ 1. -2. 43.]
 [-0.  5. -9.]
 [ 7. -9. 11.]
 [ 0.  2.  8.]]
B = 
 [[ 1 -2 43]
 [ 0  5 -9]
 [ 7 -9 11]
 [ 0  2  8]]


In [ ]:
print("B * B_обр = 1/" + str(coef_) + "\n" + str(B.dot(B_)))
BB_ = B.dot(B_/coef_)
print(BB_)

B * B_обр = 1/2526625.0
[[2361789. -251720.   23548.  570430.]
 [-251720. 2142225.   35960.  871100.]
 [  23548.   35960. 2523261.  -81490.]
 [ 570430.  871100.  -81490.  552600.]]
[[ 0.9347604  -0.09962697  0.00931994  0.22576758]
 [-0.09962697  0.84786029  0.01423242  0.34476822]
 [ 0.00931994  0.01423242  0.99866858 -0.03225251]
 [ 0.22576758  0.34476822 -0.03225251  0.21871073]]


##2.12.3

In [11]:
#инвариантность
CB = C.dot(B)
print("CB =\n", CB)

CAB = C.dot(A).dot(B)
print("\nCAB =\n", CAB)

CAAB = C.dot(A).dot(A).dot(B)
print("\nCAAB =\n", CAAB)

CAAAB = C.dot(A).dot(A).dot(A).dot(B)
print("\nCAAAB =\n", CAAAB)

CB =
 [[ 349 -401  501]
 [ 498 -631  864]]

CAB =
 [[ -104915.   394552. -3085320.]
 [ -105047.   394584. -3084564.]]

CAAB =
 [[ -1185257.           4390396.00000001 -33345858.00000013]
 [ -1197687.           4440884.00000001 -33789168.00000013]]

CAAAB =
 [[-1.08832430e+07  3.85079080e+07 -2.62386012e+08]
 [-1.10676170e+07  3.92661240e+07 -2.69433570e+08]]


##2.13

In [12]:
#дополнительные вычисления для матрицы наблюдаемости
A_arr = A.T
C_arr = C.T

AC = np.matrix(A_arr.dot(C_arr))
AAC = np.matrix(A_arr.dot(A_arr).dot(C_arr))
AAAC = np.matrix(A_arr.dot(A_arr).dot(A_arr).dot(C_arr))
print("A * C = ")
print(AC)
print('\n')

print("A * A * C = ")
print(AAC)
print('\n')
print("A * A * A * C = ")
print(AAAC)
print('\n')

A * C = 
[[-63692. -63684.]
 [ 39257.  39217.]
 [ -5889.  -5909.]
 [  8941.   8975.]]


A * A * C = 
[[-686654. -695864.]
 [ 432425.  437733.]
 [ -71229.  -71689.]
 [ 106951.  107645.]]


A * A * A * C = 
[[-5353460.00000014 -5500734.00000014]
 [ 3664229.00000003  3744241.00000003]
 [ -789969.00000001  -795269.00000001]
 [ 1185061.00000001  1193015.00000001]]




In [13]:
gamma = np.concatenate((C.T, AC, AAC, AAAC), axis=1)
print('{A, С} = ')
print(pd.DataFrame(gamma))
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C} = " + str(rang_gamma))

{A, С} = 
      0     1        2        3         4         5          6          7
0  -8.0   1.0 -63692.0 -63684.0 -686654.0 -695864.0 -5353460.0 -5500734.0
1  -4.0   0.0  39257.0  39217.0  432425.0  437733.0  3664229.0  3744241.0
2  51.0  71.0  -5889.0  -5909.0  -71229.0  -71689.0  -789969.0  -795269.0
3  31.0   5.0   8941.0   8975.0  106951.0  107645.0  1185061.0  1193015.0

Ранг матрицы наблюдаемости rg {A,C} = 4


##2.15

In [14]:
#-38 & 267 & 386 & -616
d0 = 1
d1 = -38
d2 = 267
d3 = 386

In [20]:
#нахождение матрицы S
S4 = np.round(B[:,0])
S3 = np.round(A.dot(S4) + d1 * B[:,0])
S2 = np.round(A.dot(S3) + d2 * B[:,0])
S1 = np.round(A.dot(S2) + d3 * B[:,0])
print('S_1 = ')
print(S1)
print('\nS_2 = ')
print(S2)
print('\nS_3 = ')
print(S3)
print('\nS_4 = ')
print(S4)
print('\nS = ')
S = np.concatenate((S1, S2, S3, S4), axis=1)
print(pd.DataFrame(S))

coef_S = np.round(np.linalg.det(S))
print('det(S) = ' + str(coef_S))

print('\nS_обр = 1/(' + str(coef_S) + ") * ")
S_ = np.linalg.inv(S)
print(pd.DataFrame(S_ * coef_S))

print("\nS * S_обр = ")
pd.DataFrame(np.round(S.dot(S_)))

S_1 = 
[[ 1012.]
 [ 1980.]
 [88776.]
 [57012.]]

S_2 = 
[[-1093.]
 [-2160.]
 [39253.]
 [28239.]]

S_3 = 
[[   80.]
 [  180.]
 [-1676.]
 [-1011.]]

S_4 = 
[[1]
 [0]
 [7]
 [0]]

S = 
         0        1       2    3
0   1012.0  -1093.0    80.0  1.0
1   1980.0  -2160.0   180.0  0.0
2  88776.0  39253.0 -1676.0  7.0
3  57012.0  28239.0 -1011.0  0.0
det(S) = -61994743200.0

S_обр = 1/(-61994743200.0) * 
              0             1             2             3
0  2.029482e+07 -1.572246e+07 -2.899260e+06  3.612960e+06
1 -8.584758e+07  4.488822e+07  1.226394e+07 -1.913184e+07
2 -1.253414e+09  3.671905e+08  1.790591e+08 -2.693246e+08
3 -7.609139e+10  3.559872e+10  2.013806e+09 -3.021445e+09

S * S_обр = 


0    1    2    3
0  1.0  0.0  0.0  0.0
1 -0.0  1.0 -0.0  0.0
2  0.0 -0.0  1.0  0.0
3  0.0 -0.0 -0.0  1.0

In [26]:
#-45 & -2433 & 23357 & 367920
#3-4) поиск матрицы K
d_ = [-45, -2433, 23357, 367920]
d = [-38, 267, 386, -616]
K_ = np.matrix([d_[3] - d[3], d_[2] - d[2], d_[1] - d[1], d_[0] - d[0]]) #это K с чертой (ее можно найти с помощью пункта 2)
print(K_)
K = K_.dot(S_)
print("K = 1/(" + str(coef_S) + ") *")
pd.DataFrame(K * coef_S)

[[368536  22971  -2700     -7]]
K = 1/(-61994743200.0) *


0             1             2             3
0  9.424224e+12 -6.003770e+12 -1.284323e+12  1.640355e+12

In [27]:
#5) поиск A с чертой
A_ = A - (B[:,0]).dot(K)
print("A_ = 1/(" + str(coef_S) + ") *")
print(pd.DataFrame(A_ * coef_S))

A_ = 1/(-61994743200.0) *
              0             1             2             3
0 -1.673960e+13  9.723455e+12  1.284323e+12 -1.640355e+12
1 -1.115905e+13  5.703516e+12  0.000000e+00  0.000000e+00
2 -1.284008e+13  9.355164e+12  1.388785e+13 -1.892185e+13
3  3.663889e+13 -2.306204e+13  3.719685e+12 -5.641522e+12


In [30]:
#check
lambda1 = 73
I = np.eye(4)
check1 = lambda1 * I - A_
print("lambda * I - A_ = 1/(" + str(coef_S) + ") *" + str(pd.DataFrame(check1 * coef_S)))
print('\ndet (lambda * I - A_) = ' + str(np.round(np.linalg.det(check1))))

lambda * I - A_ = 1/(-61994743200.0) *              0             1             2             3
0  1.221399e+13 -9.723455e+12 -1.284323e+12  1.640355e+12
1  1.115905e+13 -1.022913e+13  0.000000e+00  0.000000e+00
2  1.284008e+13 -9.355164e+12 -1.841346e+13  1.892185e+13
3 -3.663889e+13  2.306204e+13 -3.719685e+12  1.115905e+12

det (lambda * I - A_) = 0.0


In [31]:
lambda2 = -9
check2 = lambda2 * I - A_
print("lambda * I - A_ = 1/(" + str(coef_S) + ") *" + str(pd.DataFrame(check2*coef_S)))
print('\ndet (lambda * I - A_) = ' + str((np.round(np.linalg.det(check2)))))

lambda * I - A_ = 1/(-61994743200.0) *              0             1             2             3
0  1.729756e+13 -9.723455e+12 -1.284323e+12  1.640355e+12
1  1.115905e+13 -5.145564e+12  0.000000e+00  0.000000e+00
2  1.284008e+13 -9.355164e+12 -1.332989e+13  1.892185e+13
3 -3.663889e+13  2.306204e+13 -3.719685e+12  6.199474e+12

det (lambda * I - A_) = -0.0


In [32]:
lambda3 = 16
check3 = lambda3 * I - A_
print("lambda * I - A_ = 1/(" + str(coef_S) + ") *" + str(pd.DataFrame(check3*6233760)))
print('\ndet (lambda * I - A_) = ' + str(np.round((np.linalg.det(check3)))))

lambda * I - A_ = 1/(-61994743200.0) *              0             1             2             3
0 -1.583478e+09  9.777230e+08  1.291426e+08 -1.649427e+08
1 -1.122077e+09  6.732461e+08  0.000000e+00  0.000000e+00
2 -1.291109e+09  9.406902e+08  1.496205e+09 -1.902650e+09
3  3.684152e+09 -2.318959e+09  3.740256e+08 -4.675320e+08

det (lambda * I - A_) = -0.0


In [33]:
lambda4 = -35
check4 = lambda4 * I - A_
print("lambda * I - A_ = 1/(" + str(coef_S) + ") *" + str(pd.DataFrame(check4*6233760)))
print('\ndet (lambda * I - A_) = ' + str((np.round(np.linalg.det(check4)))))

lambda * I - A_ = 1/(-61994743200.0) *              0             1             2             3
0 -1.901400e+09  9.777230e+08  1.291426e+08 -1.649427e+08
1 -1.122077e+09  3.553243e+08  0.000000e+00  0.000000e+00
2 -1.291109e+09  9.406902e+08  1.178284e+09 -1.902650e+09
3  3.684152e+09 -2.318959e+09  3.740256e+08 -7.854538e+08

det (lambda * I - A_) = -0.0
