<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab3_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import math

##1.1

In [29]:
#дана система, где
A = np.matrix([[84, -20],[-49, -10]])
B = np.matrix([701, 5]).T

print("A =\n", A)
print("B =\n", B)

A =
 [[ 84 -20]
 [-49 -10]]
B =
 [[701]
 [  5]]


In [30]:
#характеристический многочлен:
print("det(p*I-A)=\n=[[p-84, 20],[49, p+10]]=")
print("=(p-84)(p+10)-20*49=")
print("=p^2-74p-840-980=p^2-74p-1820=")
print("=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))")


det(p*I-A)=
=[[p-84, 20],[49, p+10]]=
=(p-84)(p+10)-20*49=
=p^2-74p-840-980=p^2-74p-1820=
=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))


In [31]:
d1 = -74
d2 = -1820
p1 = 37 + math.sqrt(3189)
p2 = 37 - math.sqrt(3189)

print("d1 = ", d1)
print("d2 = ", d2)
print("p1 = ", p1)
print("p2 = ", p2)
#система неустойчива, тк один из корней положительный

d1 =  -74
d2 =  -1820
p1 =  93.471231613982
p2 =  -19.471231613982


In [32]:
#матрица управляемости:
#доп вычисления:
AB = A.dot(B)
print('A*B =\n', AB)
#n=2

A*B =
 [[ 58784]
 [-34399]]


In [33]:
#матрица управляемости:
beta = np.concatenate((np.round(B), np.round(AB)), axis=1)
print("{A,B}_u = ")
print(beta)

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))
#система вполне управляема

{A,B}_u = 
[[   701  58784]
 [     5 -34399]]

Ранг матрицы управляемости rg {A,B} = 2


In [34]:
#зададим собственные числа, удовл. критерию устойчивости непр. систем
lambda_ = np.matrix([[-96,0],[0,-172]])
print("Матрица собственных чисел:\n", lambda_)

Матрица собственных чисел:
 [[ -96    0]
 [   0 -172]]


In [35]:
#определим матрицу F:
f2 = B.copy()
f1 = A.dot(f2) + d1 * B
F = np.concatenate((np.round(f1), np.round(f2)), axis=1)
print("F = ")
print(F)

F = 
[[  6910    701]
 [-34769      5]]


In [36]:
#найдём F^{-1}
det_F = np.round(np.linalg.det(F))
F_ = np.linalg.inv(F)
FF_ = F.dot(F_)
print("det(F) = ", det_F)
print("\nF_обр = 1/" + str(det_F) + " * \n" + str(pd.DataFrame(np.round(F_*det_F))))
print("\nF * F_обр = \n", np.round(FF_))

det(F) =  24407619.0

F_обр = 1/24407619.0 * 
         0       1
0      5.0  -701.0
1  34769.0  6910.0

F * F_обр = 
 [[ 1. -0.]
 [-0.  1.]]


In [37]:
#определим коэффициенты d_
print("(p+96)*(p+172)=p^2 + 268p + 16512")
d1_ = 268
d2_ = 16512

(p+96)*(p+172)=p^2 + 268p + 16512


In [38]:
#срсиавим строку K_:
K_ = np.matrix([d2_-d2, d1_-d1])
print("K_ = ", K_)

K = K_.dot(F_)
print("K = 1/" + str(det_F) + " * \n" + str(K*det_F))

K_ =  [[18332   342]]
K = 1/24407619.0 * 
[[ 11982658. -10487512.]]


In [ ]:
#u = K * x
#желательно, чтобы матрицы K и K_ были целые (надо выносить множитель ещё у F_)

In [39]:
#контроль
A_ = A - B.dot(K)
print("A_ = 1/" + str(det_F) + " * \n" + str(pd.DataFrame(np.round(A_*det_F))))

print("\ndet(p*I-A_) = 1/" + str(det_F) + "[[24407619p+....],[]]")

A_ = 1/24407619.0 * 
              0             1
0 -6.349603e+09  6.863594e+09
1 -1.255887e+09 -1.916386e+08

det(p*I-A_) = 1/24407619.0[[24407619p+....],[]]


##1.2

In [40]:
#дана система с прежними А и В. И добавляется к ней:
C = np.matrix([-38, 99])
print("C = \n", C)
#система неустойчива и вполне управляема (из пункта 1.1)

C = 
 [[-38  99]]


In [41]:
#матрица наблюдаемости
A_arr = A.copy().T
C_arr = C.copy().T

AC = np.matrix(A_arr.dot(C_arr))
print("A * C = \n", AC)

gamma = np.concatenate((C.T, AC), axis=1)
print('\n{A, С} = \n', gamma)
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C}_y = " + str(rang_gamma))
#система вполне наблюдаема

A * C = 
 [[-8043]
 [ -230]]

{A, С} = 
 [[  -38 -8043]
 [   99  -230]]

Ранг матрицы наблюдаемости rg {A,C}_y = 2


In [43]:
#определим мотрицу Fd - F с домиком
f2d = C.copy().T
f1d = (A.T).dot(f2d) + d1 * (C.T)
Fd = np.concatenate((np.round(f1d), np.round(f2d)), axis=1)
print("F^ = \n", Fd)

F^ = 
 [[-5231   -38]
 [-7556    99]]


In [44]:
#найдём F^{-1}
det_Fd = np.round(np.linalg.det(Fd))
Fd_ = np.linalg.inv(Fd)
FdFd_ = Fd.dot(Fd_)
print("det(F^) = ", det_Fd)
print("\nF^_обр = 1/" + str(det_Fd) + " * \n" + str(pd.DataFrame(np.round(Fd_*det_Fd))))
print("\nF^ * F^_обр = \n", np.round(FdFd_))

det(F^) =  -804997.0

F^_обр = 1/-804997.0 * 
        0       1
0    99.0    38.0
1  7556.0 -5231.0

F^ * F^_обр = 
 [[1. 0.]
 [0. 1.]]
