<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab3_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import math

##1.1

In [2]:
#дана система, где
A = np.matrix([[84, -20],[-49, -10]])
B = np.matrix([701, 5]).T

print("A =\n", A)
print("B =\n", B)

A =
 [[ 84 -20]
 [-49 -10]]
B =
 [[701]
 [  5]]


In [3]:
#характеристический многочлен:
print("det(p*I-A)=\n=[[p-84, 20],[49, p+10]]=")
print("=(p-84)(p+10)-20*49=")
print("=p^2-74p-840-980=p^2-74p-1820=")
print("=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))")


det(p*I-A)=
=[[p-84, 20],[49, p+10]]=
=(p-84)(p+10)-20*49=
=p^2-74p-840-980=p^2-74p-1820=
=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))


In [4]:
d1 = -74
d2 = -1820
p1 = 37 + math.sqrt(3189)
p2 = 37 - math.sqrt(3189)

print("d1 = ", d1)
print("d2 = ", d2)
print("p1 = ", p1)
print("p2 = ", p2)
#система неустойчива, тк один из корней положительный

d1 =  -74
d2 =  -1820
p1 =  93.471231613982
p2 =  -19.471231613982


In [5]:
#матрица управляемости:
#доп вычисления:
AB = A.dot(B)
print('A*B =\n', AB)
#n=2

A*B =
 [[ 58784]
 [-34399]]


In [6]:
#матрица управляемости:
beta = np.concatenate((np.round(B), np.round(AB)), axis=1)
print("{A,B}_u = ")
print(beta)

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))
#система вполне управляема

{A,B}_u = 
[[   701  58784]
 [     5 -34399]]

Ранг матрицы управляемости rg {A,B} = 2


In [7]:
#зададим собственные числа, удовл. критерию устойчивости непр. систем
lambda_ = np.matrix([[-96,0],[0,-172]])
print("Матрица собственных чисел:\n", lambda_)

Матрица собственных чисел:
 [[ -96    0]
 [   0 -172]]


In [8]:
#определим матрицу F:
f2 = B.copy()
f1 = A.dot(f2) + d1 * B
F = np.concatenate((np.round(f1), np.round(f2)), axis=1)
print("F = ")
print(F)

F = 
[[  6910    701]
 [-34769      5]]


In [9]:
#найдём F^{-1}
det_F = np.round(np.linalg.det(F))
F_ = np.linalg.inv(F)
FF_ = F.dot(F_)
print("det(F) = ", det_F)
print("\nF_обр = 1/" + str(det_F) + " * \n" + str(pd.DataFrame(np.round(F_*det_F))))
print("\nF * F_обр = \n", np.round(FF_))

det(F) =  24407619.0

F_обр = 1/24407619.0 * 
         0       1
0      5.0  -701.0
1  34769.0  6910.0

F * F_обр = 
 [[ 1. -0.]
 [-0.  1.]]


In [10]:
#определим коэффициенты d_
print("(p+96)*(p+172)=p^2 + 268p + 16512")
d1_ = 268
d2_ = 16512

(p+96)*(p+172)=p^2 + 268p + 16512


In [11]:
#срсиавим строку K_:
K_ = np.matrix([d2_-d2, d1_-d1])
print("K_ = ", K_)

K = K_.dot(F_)
print("K = 1/" + str(det_F) + " * \n" + str(K*det_F))

K_ =  [[18332   342]]
K = 1/24407619.0 * 
[[ 11982658. -10487512.]]


In [12]:
#u = K * x
#желательно, чтобы матрицы K и K_ были целые (надо выносить множитель ещё у F_)

In [13]:
#контроль
A_ = A - B.dot(K)
print("A_ = 1/" + str(det_F) + " * \n" + str(pd.DataFrame(np.round(A_*det_F))))

print("\ndet(p*I-A_) = 1/" + str(det_F) + "[[24407619p+....],[]]")

A_ = 1/24407619.0 * 
              0             1
0 -6.349603e+09  6.863594e+09
1 -1.255887e+09 -1.916386e+08

det(p*I-A_) = 1/24407619.0[[24407619p+....],[]]


In [19]:
#контроль
a0 = (A.copy())*det_F
print(a0)
bk = np.matrix([[8399843258, -7351745912],[59913290, -52437560]])
print(bk)
aa_ = a0-bk
print(aa_)
print(aa_/det_F)

[[ 2.05024000e+09 -4.88152380e+08]
 [-1.19597333e+09 -2.44076190e+08]]
[[ 8399843258 -7351745912]
 [   59913290   -52437560]]
[[-6.34960326e+09  6.86359353e+09]
 [-1.25588662e+09 -1.91638630e+08]]
[[-260.14840948  281.20700884]
 [ -51.45469622   -7.85159052]]


In [18]:
print(6349603262*191638630)
print(6863593532+1255886621)
print(1216829270173211060+8119480153)

1216829270173211060
8119480153
1216829278292691213


##1.2

In [20]:
#дана система с прежними А и В. И добавляется к ней:
C = np.matrix([-38, 99])
print("C = \n", C)
#система неустойчива и вполне управляема (из пункта 1.1)

C = 
 [[-38  99]]


In [21]:
#матрица наблюдаемости
A_arr = A.copy().T
C_arr = C.copy().T

AC = np.matrix(A_arr.dot(C_arr))
print("A * C = \n", AC)

gamma = np.concatenate((C.T, AC), axis=1)
print('\n{A, С} = \n', gamma)
rang_gamma = np.linalg.matrix_rank(gamma)
print("\nРанг матрицы наблюдаемости rg {A,C}_y = " + str(rang_gamma))
#система вполне наблюдаема

A * C = 
 [[-8043]
 [ -230]]

{A, С} = 
 [[  -38 -8043]
 [   99  -230]]

Ранг матрицы наблюдаемости rg {A,C}_y = 2


In [23]:
#определим мотрицу Fd - F с домиком
f2d = C.copy().T
print(f2d)
f1d = (A.T).dot(f2d) + d1 * (C.T)
print(f1d)
Fd = np.concatenate((np.round(f1d), np.round(f2d)), axis=1)
print("F^ = \n", Fd)

[[-38]
 [ 99]]
[[-5231]
 [-7556]]
F^ = 
 [[-5231   -38]
 [-7556    99]]


In [24]:
#найдём F^{-1}
det_Fd = np.round(np.linalg.det(Fd))
Fd_ = np.linalg.inv(Fd)
FdFd_ = Fd.dot(Fd_)
print("det(F^) = ", det_Fd)
print("\nF^_обр = 1/" + str(det_Fd) + " * \n" + str(pd.DataFrame(np.round(Fd_*det_Fd))))
print("\nF^ * F^_обр = \n", np.round(FdFd_))

det(F^) =  -804997.0

F^_обр = 1/-804997.0 * 
        0       1
0    99.0    38.0
1  7556.0 -5231.0

F^ * F^_обр = 
 [[1. 0.]
 [0. 1.]]


In [25]:
#пусть матрица из собственных чисел lambda^ выглядит так:
lambda_d = np.matrix([[-3,0],[0,-801]])
print("Матрица собственных чисел:\n", lambda_d)

Матрица собственных чисел:
 [[  -3    0]
 [   0 -801]]


In [26]:
#определим коэффициенты d^:
print("(p+3)*(p+801)=p^2 + 804p + 2403")
d1d = 804
d2d = 2403

(p+3)*(p+801)=p^2 + 804p + 2403


In [27]:
#пусть K^ = L^ = 
Ld = np.matrix([d2d-d2, d1d-d1])
print("L^ = ", Ld)

L = Ld.dot(Fd_).T
print("\nL = 1/" + str(det_Fd) + " * \n" + str(L*det_Fd))

L^ =  [[4223  878]]

L = 1/-804997.0 * 
[[ 7052245.]
 [-4432344.]]


In [42]:
#контроль:
Ad = A - L.dot(C)
lc = L.dot(C)
print(lc)
print("A^ = 1/" + str(det_Fd) + " * \n" + str(pd.DataFrame(np.round(Ad*det_Fd))))

print("\ndet(p*I-A_) = 1/" + str(det_Fd) + "[[...],[]]")

[[ 332.90224684 -867.29795887]
 [-209.22944061  545.09775316]]
A^ = 1/-804997.0 * 
             0            1
0  200365562.0 -682072315.0
1 -128984219.0  446852026.0

det(p*I-A_) = 1/-804997.0[[...],[]]


In [41]:
#искомый алгоритм управления:
print("u^ = K * x^")
#далее разложение с х и у

u^ = K * x^


In [68]:
a_bk = np.matrix([[-6349603262, 6863593532],[-1255886621, -191638630]])
_lc = np.round((L.dot(C))*det_Fd)
coeff = det_F*det_Fd
#print(a_bk)
#print(_lc)
print(coeff)
clog1 = a_bk*det_Fd
#print(clog1)
clog2 = _lc*det_F
#print(clog2)
sum = clog1+clog2
print(sum)

-19648060072143.0
[[-1.42947177e+15  1.15155502e+16]
 [ 5.12193758e+15 -1.05558449e+16]]


##1.3

In [70]:
#дана система:
Aa = np.matrix([[0, -49],[36, 0]])
Bb = np.matrix([[0],[76]])
x0 = np.matrix([[0],[7]])
print('A = \n', Aa)
print('\nB = \n', Bb)
print('\nx0 = \n', x0)

A = 
 [[  0 -49]
 [ 36   0]]

B = 
 [[ 0]
 [76]]

x0 = 
 [[0]
 [7]]


In [ ]:
#показатель качества:
#J_1\{u\} = \int_0^{\infty} \{ 7x_1^2(t) + 2x_2^2(t) - 5u^2(t)\} dt

In [72]:
#матрица управляемости
AaBb = Aa.dot(Bb)
alpha = np.concatenate((np.round(Bb), np.round(AaBb)), axis=1)
print("{A,B}_u = ")
print(alpha)

rang_alpha = np.linalg.matrix_rank(alpha)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_alpha))
#система вполне управляема

{A,B}_u = 
[[    0 -3724]
 [   76     0]]

Ранг матрицы управляемости rg {A,B} = 2
