<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab3_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import math

##1.1

In [12]:
#дана система, где
A = np.matrix([[84, -20],[-49, -10]])
B = np.matrix([701, 5]).T

print("A =\n", A)
print("B =\n", B)

A =
 [[ 84 -20]
 [-49 -10]]
B =
 [[701]
 [  5]]


In [13]:
#характеристический многочлен:
print("det(p*I-A)=\n=[[p-84, 20],[49, p+10]]=")
print("=(p-84)(p+10)-20*49=")
print("=p^2-74p-840-980=p^2-74p-1820=")
print("=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))")


det(p*I-A)=
=[[p-84, 20],[49, p+10]]=
=(p-84)(p+10)-20*49=
=p^2-74p-840-980=p^2-74p-1820=
=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))


In [17]:
d1 = -74
d2 = -1820
p1 = 37 + math.sqrt(3189)
p2 = 37 - math.sqrt(3189)

print("d1 = ", d1)
print("d2 = ", d2)
print("p1 = ", p1)
print("p2 = ", p2)
#система неустойчива, тк один из корней положительный

d1 =  -74
d2 =  -1820
p1 =  93.471231613982
p2 =  -19.471231613982


In [18]:
#матрица управляемости:
#доп вычисления:
AB = A.dot(B)
print('A*B =\n', AB)
#n=2

A*B =
 [[ 58784]
 [-34399]]


In [23]:
#матрица управляемости:
beta = np.concatenate((np.round(B), np.round(AB)), axis=1)
print("{A,B}_u = ")
print(beta)

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))
#система вполне управляема

{A,B}_u = 
[[   701  58784]
 [     5 -34399]]

Ранг матрицы управляемости rg {A,B} = 2
