<a href="https://colab.research.google.com/github/Viktory4121/Control_theory/blob/main/lab3_ct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd
import numpy as np
import math

##1.1

In [12]:
#дана система, где
A = np.matrix([[84, -20],[-49, -10]])
B = np.matrix([701, 5]).T

print("A =\n", A)
print("B =\n", B)

A =
 [[ 84 -20]
 [-49 -10]]
B =
 [[701]
 [  5]]


In [13]:
#характеристический многочлен:
print("det(p*I-A)=\n=[[p-84, 20],[49, p+10]]=")
print("=(p-84)(p+10)-20*49=")
print("=p^2-74p-840-980=p^2-74p-1820=")
print("=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))")


det(p*I-A)=
=[[p-84, 20],[49, p+10]]=
=(p-84)(p+10)-20*49=
=p^2-74p-840-980=p^2-74p-1820=
=(p - 37 + sqrt(3189))*(p - 37 - sqrt(3189))


In [17]:
d1 = -74
d2 = -1820
p1 = 37 + math.sqrt(3189)
p2 = 37 - math.sqrt(3189)

print("d1 = ", d1)
print("d2 = ", d2)
print("p1 = ", p1)
print("p2 = ", p2)
#система неустойчива, тк один из корней положительный

d1 =  -74
d2 =  -1820
p1 =  93.471231613982
p2 =  -19.471231613982


In [18]:
#матрица управляемости:
#доп вычисления:
AB = A.dot(B)
print('A*B =\n', AB)
#n=2

A*B =
 [[ 58784]
 [-34399]]


In [23]:
#матрица управляемости:
beta = np.concatenate((np.round(B), np.round(AB)), axis=1)
print("{A,B}_u = ")
print(beta)

rang_beta = np.linalg.matrix_rank(beta)
print("\nРанг матрицы управляемости rg {A,B} = " + str(rang_beta))
#система вполне управляема

{A,B}_u = 
[[   701  58784]
 [     5 -34399]]

Ранг матрицы управляемости rg {A,B} = 2


In [30]:
#зададим собственные числа, удовл. критерию устойчивости непр. систем
lambda_ = np.matrix([[-96,0],[0,-172]])
print("Матрица собственных чисел:\n", lambda_)

Матрица собственных чисел:
 [[ -96    0]
 [   0 -172]]


In [31]:
#определим матрицу F:
f2 = B.copy()
f1 = A.dot(f2) + d1 * B
F = np.concatenate((np.round(f1), np.round(f2)), axis=1)
print("F = ")
print(F)

F = 
[[  6910    701]
 [-34769      5]]


In [37]:
#найдём F^{-1}
det_F = np.linalg.det(F)
F_ = np.linalg.inv(F)
FF_ = F.dot(F_)
print("det(F) = ", det_F)
print("\nF_обр = \n", F_)
print("\nF * F_обр = \n", np.round(FF_))

det(F) =  24407618.999999978

F_обр = 
 [[ 2.04854066e-07 -2.87205401e-05]
 [ 1.42451421e-03  2.83108320e-04]]

F * F_обр = 
 [[ 1. -0.]
 [-0.  1.]]


In [38]:
#определим коэффициенты d_
print("(p+96)*(p+172)=p^2 + 268p + 16512")
d1_ = 268
d2_ = 16512

(p+96)*(p+172)=p^2 + 268p + 16512


In [39]:
#срсиавим строку K_:
K_ = np.matrix([d2_-d2, d1_-d1])
print("K_ = ", K_)

K = K_.dot(F_)
print("K = ", K)

K_ =  [[18332   342]]
K =  [[ 0.49093924 -0.4296819 ]]


In [ ]:
#u = K * x
#желательно, чтобы матрицы K и K_ были целые (надо выносить множитель ещё у F_)

In [40]:
#контроль
A_ = A - B.dot(K)
print("A_ = \n", A_)

print("\ndet")

A_ = 
 [[-260.14840948  281.20700884]
 [ -51.45469622   -7.85159052]]

det
